In [37]:
from ase.visualize import view
from ase.build import graphene

import numpy as np

from mace.calculators import MACECalculator

from ase.optimize import BFGS

In [39]:
calc = MACECalculator("../../MACE.model", device="cuda")

atoms = graphene()
atoms.calc = calc

opt = BFGS(atoms)
opt.run(fmax=1e-3)
view(atoms, viewer="x3d")

/home/gabri/anaconda3/envs/mace/lib/python3.10/site-packages/mace/calculators/mace.py:199: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  torch.load(f=model_path, map_location=device)


      Step     Time          Energy          fmax
BFGS:    0 19:11:21      -15.917213        0.000013


In [30]:
cell0 = atoms.cell.copy()
cell = atoms.cell

In [31]:
atoms.cell

Cell([[2.46, 0.0, 0.0], [-1.23, 2.130422493309719, 0.0], [0.0, 0.0, 0.0]])

In [32]:
print(cell0)

Cell([[2.46, 0.0, 0.0], [-1.23, 2.130422493309719, 0.0], [0.0, 0.0, 0.0]])


In [35]:
strain = np.array([
    [0.3, 0,0],
    [0,0.,0],
    [0,0,0]
])

atoms.set_cell((np.eye(3) + strain) @ cell0, scale_atoms=True)
atoms.calc = calc

opt = BFGS(atoms)
opt.run(fmax=1e-3)

stress = atoms.get_stress(voigt=False)

print(atoms.cell)
print(np.linalg.norm(atoms.cell, axis = -1))
print(stress)
print(np.trace(stress.T @ stress))
view(atoms, viewer="x3d")

      Step     Time          Energy          fmax
BFGS:    0 19:08:37      -10.331902        3.700886
BFGS:    1 19:08:38      -10.794817        4.954633
BFGS:    2 19:08:38      -12.863136        3.741462
BFGS:    3 19:08:38      -12.167315       16.716194
BFGS:    4 19:08:38      -13.333519        1.781828
BFGS:    5 19:08:38      -13.457369        1.204544
BFGS:    6 19:08:38      -13.583970        0.552999
BFGS:    7 19:08:38      -13.594076        0.175977
BFGS:    8 19:08:38      -13.595917        0.021765
BFGS:    9 19:08:38      -13.595983        0.005867
BFGS:   10 19:08:38      -13.595984        0.000389
Cell([[3.198, 0.0, 0.0], [-1.23, 2.130422493309719, 0.0], [0.0, 0.0, 0.0]])
[3.198 2.46  0.   ]
[[-4.5219129e-03  3.6719621e-03 -1.6029630e-23]
 [ 3.6719621e-03 -9.8368824e-03  2.2057791e-23]
 [-1.6029630e-23  2.2057791e-23  8.3419555e-36]]
0.00014417856


In [34]:
atoms.positions

array([[-6.26747265e-02,  3.38407608e-01,  2.01478276e-17],
       [ 1.16967473e+00,  5.84775416e-01,  6.84008920e-18]])